import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

/** SPEC-338: the brand files the app serves are copies. This is what keeps
 *  them from silently becoming forks.
 *
 *  `brand/README.md` states the kit is generated by `brand/tools/build.py`
 *  and never hand-edited, and `brand/` sits outside `apps/tauri-ui`, so Vite
 *  cannot serve from it directly. Copying into `public/` is the mechanism;
 *  the risk the spec names is that a copy goes stale when Rev B is
 *  generated, with nothing to say so. These tests are that something.
 *
 *  They caught a real one on the way in: `public/favicon.svg` was a purple
 *  `#863bff` mark left over from a template, shipping as the app's icon
 *  since before the product had this name. */
const HERE = path.dirname(fileURLToPath(import.meta.url))
const APP = path.join(HERE, '..')
const KIT = path.join(APP, '..', '..', 'brand', 'svg')

/** served file -> the generated file in the kit it must equal */
const COPIES = {
  'favicon.svg': 'favicon.svg',
  'brand-mark.svg': 'mark.svg',
  'brand-mark-on-dark.svg': 'mark-on-dark.svg',
}

function strokeOf(svg: string): string {
  const match = svg.match(/stroke="(#[0-9a-fA-F]{6})"/)
  if (!match) throw new Error('no stroke colour in that SVG')
  return match[1].toLowerCase()
}

function token(selector: string, name: string): string {
  const css = fs.readFileSync(path.join(APP, 'src', 'index.css'), 'utf8')
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const start = css.search(new RegExp(`^[ \\t]*${escaped}\\s*\\{`, 'm'))
  let depth = 0
  for (let i = css.indexOf('{', start); i < css.length; i++) {
    if (css[i] === '{') depth++
    else if (css[i] === '}' && --depth === 0) {
      const match = css.slice(start, i).match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{6})`))
      if (!match) throw new Error(`no --color-${name} in ${selector}`)
      return match[1].toLowerCase()
    }
  }
  throw new Error(`${selector} never closes`)
}

describe('brand assets', () => {
  it.each(Object.entries(COPIES))(
    'public/%s is byte-identical to the generated brand/svg/%s',
    (served, generated) => {
      const a = fs.readFileSync(path.join(APP, 'public', served))
      const b = fs.readFileSync(path.join(KIT, generated))

      // Not a similarity check. If the kit is regenerated and this copy is
      // not refreshed, the app ships the old mark and this fails.
      expect(a.equals(b)).toBe(true)
    },
  )

  it('the mark on light surfaces is drawn in the light theme brand colour', () => {
    const svg = fs.readFileSync(path.join(APP, 'public', 'brand-mark.svg'), 'utf8')

    expect(strokeOf(svg)).toEqual(token(':root[data-theme="light"]', 'brand'))
  })

  it('the mark on dark surfaces is drawn in the dark theme brand colour', () => {
    const svg = fs.readFileSync(path.join(APP, 'public', 'brand-mark-on-dark.svg'), 'utf8')

    expect(strokeOf(svg)).toEqual(token('@theme', 'brand'))
  })

  it('the two marks are not the same file', () => {
    const light = fs.readFileSync(path.join(APP, 'public', 'brand-mark.svg'))
    const dark = fs.readFileSync(path.join(APP, 'public', 'brand-mark-on-dark.svg'))

    // They are 549 bytes each and differ only in the stroke colour and a
    // mask id, which is exactly the shape of a copy-paste mistake.
    expect(light.equals(dark)).toBe(false)
  })
})
