"""Generate and *verify* a `<project>.kicad_dru` sidecar -- SPEC-114, CTX-114.1 Phase 1.

The reason this module exists before any capability-profile object does is
`SPEC-114` section 2.2, Limit 2, measured against KiCad 10.0.3: **a malformed
`.kicad_dru` is discarded entirely and silently**. One misspelled constraint
name drops every other rule in the file, with nothing on stderr and an
unchanged exit code. So writing the sidecar is not the deliverable -- writing
it and proving the rules actually took effect is.

The hard part is that "my rule found nothing" and "my file was thrown away"
look *identical* from the outside: both are a report with no findings of ours.
Asserting "every rule must produce a violation" would be wrong -- a rule that
finds nothing on a compliant board is the normal, desirable case, and
`courtyard_clearance` at 1mm legitimately finds nothing on the example board.

So every file this module writes carries a **canary**: one extra rule, owned by
us and stripped from the results, set to a threshold no real board can satisfy.
The canary's presence in the report proves the file parsed; its absence proves
it did not. That distinction is measured, not assumed -- see the module tests.

`stdout` is the JSON-RPC wire (`CLAUDE.md`), so nothing here ever prints.
"""

import collections
import logging
import os
import re

import kicad_cli

logger = logging.getLogger(__name__)


class SidecarError(Exception):
    """Base for sidecar problems."""


class SidecarDiscarded(SidecarError):
    """The sidecar was written but KiCad silently threw it away.

    Raised when the canary did not appear in a report that a canary-only
    control run proves it should have. This is Limit 2 firing for real, and it
    must always reach the user: the alternative is reporting a strengthened
    check while every rule sits disabled."""


class SidecarWouldOverwrite(SidecarError):
    """A `.kicad_dru` exists that this app did not write.

    `SPEC-114` section 2.2 is explicit that v1 never writes a file the user
    authored. Their design rules are theirs."""


# Constraint classes confirmed firing against KiCad 10.0.3 on the example board
# (SPEC-114 section 2.1). `via_diameter` and `thermal_spoke_width` are omitted
# deliberately: they are *untested* rather than unsupported, because the example
# board has no vias and no zones. Adding them here without a run that could have
# failed would be exactly the "check that cannot fail" trap CLAUDE.md names.
CONFIRMED_CONSTRAINTS = (
    "track_width",
    "clearance",
    "annular_width",
    "hole_size",
    "hole_to_hole",
    "text_height",
    "text_thickness",
    "edge_clearance",
    "silk_clearance",
    "physical_clearance",
    "courtyard_clearance",
    "connection_width",
)

# Recorded and displayed, but never emitted as a rule: section 2.6 measured that
# these have no matching DRC constraint class at all. Saying so beats dropping
# them quietly.
UNENFORCEABLE_FIELDS = ("mask_dam", "mask_expansion")

GENERATED_MARKER = "copperplane-generated"
_HEADER = (
    "# Generated by Copperplane -- do not edit by hand.\n"
    "# Your own edits will be overwritten. marker: {marker}\n"
    "(version 1)\n"
)

CANARY_RULE_NAME = "copperplane-verification-canary"
# A threshold no real board satisfies, so the canary's absence is meaningful.
_CANARY_RULE = (
    '(rule "{name}"\n'
    "  (constraint {constraint} (min 500mm))\n"
    "  (severity warning))\n"
)

# Measured: for a given constraint class the LAST matching rule wins, and rules
# on different classes do not interfere. A canary sharing a class with a real
# rule therefore *overrides the very rule it exists to verify* -- which is what
# the first run of these tests actually did. So the canary prefers a class the
# profile is not using.
#
# Every class below was measured firing at both 10mm and 500mm on the example
# board. `connection_width` is deliberately absent: it fires 4 times at 1mm but
# ZERO times at 10mm and 500mm, so an "absurdly large minimum always fires"
# canary built on it would silently never fire and report every healthy file as
# discarded. That assumption held for six classes and was false for the seventh.
_CANARY_CANDIDATES = (
    "track_width",
    "text_height",
    "annular_width",
    "text_thickness",
    "edge_clearance",
    "hole_size",
    "clearance",
)

_RULE_NAME_RE = re.compile(r"rule '([^']+)'")

# What `verify` concluded. INDETERMINATE is a real, honest outcome, not a
# failure to try: on a board with no copper track the canary has nothing to
# catch, so the file's fate genuinely cannot be observed this way.
APPLIED = "applied"
DISCARDED = "discarded"
INDETERMINATE = "indeterminate"


def sidecar_path_for(pcb_path: str) -> str:
    """The one filename KiCad will honour, beside the board.

    Measured in section 2.1: a sidecar under any other name changes nothing, so
    this is load-bearing rather than a convention."""
    base, _ = os.path.splitext(pcb_path)
    return base + ".kicad_dru"


def pick_canary_constraint(rules):
    """A constraint class the profile is not using, or None if there is none.

    None is not an error: it means the canary would have to override one of the
    profile's own rules, so verification takes two runs instead of one. A full
    profile really does use every candidate class -- that is the normal case for
    this feature, not an edge case."""
    used = {constraint for _, constraint, _, _ in rules}
    for candidate in _CANARY_CANDIDATES:
        if candidate not in used:
            return candidate
    return None


def render_sidecar(rules, include_canary: bool = True) -> str:
    """Render `rules` as `.kicad_dru` text.

    `rules` is a sequence of (name, constraint, expression, severity) tuples,
    e.g. ("min-annular-ring", "annular_width", "min 0.13mm", "warning")."""
    rules = list(rules)
    parts = [_HEADER.format(marker=GENERATED_MARKER)]
    for name, constraint, expression, severity in rules:
        if constraint not in CONFIRMED_CONSTRAINTS:
            # Refuse to emit a class no run has confirmed. A typo here is the
            # exact input that silently disables the whole file.
            raise SidecarError(
                f"Refusing to emit unconfirmed constraint class {constraint!r}. "
                f"Confirmed classes are: {', '.join(CONFIRMED_CONSTRAINTS)}."
            )
        parts.append(
            f'(rule "{name}"\n'
            f"  (constraint {constraint} ({expression}))\n"
            f"  (severity {severity}))\n"
        )
    if include_canary:
        # Falls back to the first candidate, which the profile is then using
        # too. Last-rule-wins means the canary overrides it, so that run's
        # findings are only good for verification -- `write_and_verify` re-runs
        # without the canary to get the real ones.
        constraint = pick_canary_constraint(rules) or _CANARY_CANDIDATES[0]
        parts.append(_CANARY_RULE.format(
            name=CANARY_RULE_NAME, constraint=constraint
        ))
    return "\n".join(parts)


def rule_hits(report: dict) -> collections.Counter:
    """Count violations per *named* sidecar rule.

    Each violation's own description names the rule that produced it, e.g.
    `Annular width (rule 'min-annular-ring' min annular width 0.1300 mm; ...)`,
    which is what makes verification a substring match rather than a parser.
    KiCad's own built-in findings carry no rule name and are not counted."""
    hits = collections.Counter()
    for violation in report.get("violations", []):
        match = _RULE_NAME_RE.search(violation.get("description", ""))
        if match:
            hits[match.group(1)] += 1
    return hits


def strip_canary(report: dict) -> dict:
    """Remove the canary's own findings, which are ours and not the user's."""
    kept = [
        v for v in report.get("violations", [])
        if f"rule '{CANARY_RULE_NAME}'" not in v.get("description", "")
    ]
    trimmed = dict(report)
    trimmed["violations"] = kept
    return trimmed


def _canary_fires_on(pcb_path: str) -> bool:
    """Control run: does a canary-*only* sidecar fire on this board?

    This is what separates "KiCad discarded my file" from "this board has no
    track for the canary to catch". It is only ever needed on the failure path,
    so the normal case still costs exactly one DRC run."""
    path = sidecar_path_for(pcb_path)
    previous = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            previous = handle.read()
    try:
        control = _HEADER.format(marker=GENERATED_MARKER) + "\n" + _CANARY_RULE.format(
            name=CANARY_RULE_NAME, constraint=_CANARY_CANDIDATES[0]
        )
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(control)
        report = kicad_cli.run_drc(pcb_path)
        return rule_hits(report)[CANARY_RULE_NAME] > 0
    finally:
        if previous is None:
            os.remove(path)
        else:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(previous)


def is_generated(path: str) -> bool:
    """True when this sidecar is one of ours and safe to replace."""
    if not os.path.exists(path):
        return True
    with open(path, encoding="utf-8") as handle:
        return GENERATED_MARKER in handle.read(4096)


def write_and_verify(pcb_path: str, rules, allow_overwrite: bool = False,
                     schematic_parity: bool = False) -> dict:
    """Write the sidecar, run DRC, and prove the rules actually took effect.

    Returns a dict with `state`, the canary-stripped `report`, and `hits`, the
    per-rule violation counts. A rule that appears with zero hits found nothing
    -- which is a real result, not a failure.

    Raises `SidecarDiscarded` when the file was silently thrown away, because
    the one outcome this feature may never produce is a confident report drawn
    from rules that were never running."""
    rules = list(rules)
    path = sidecar_path_for(pcb_path)
    if not allow_overwrite and not is_generated(path):
        raise SidecarWouldOverwrite(
            f"{path} was not written by this app and will not be overwritten."
        )

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(render_sidecar(rules, include_canary=True))

    report = kicad_cli.run_drc(pcb_path, schematic_parity=schematic_parity)
    hits = rule_hits(report)
    canary_shares_a_class = pick_canary_constraint(rules) is None

    if hits[CANARY_RULE_NAME] > 0:
        state = APPLIED
        if canary_shares_a_class:
            # The canary overrode one of the profile's own rules, so this run's
            # findings are not the user's. Re-run without it for the real ones.
            # Sound because the verified file is this one plus a trailing
            # well-formed rule: removing that rule cannot introduce a parse
            # error, so the rules just proven to parse are the rules that run.
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(render_sidecar(rules, include_canary=False))
            report = kicad_cli.run_drc(pcb_path, schematic_parity=schematic_parity)
            hits = rule_hits(report)
    elif _canary_fires_on(pcb_path):
        # The canary can fire on this board, but did not fire alongside our
        # rules. That is Limit 2: something in the file is malformed and KiCad
        # discarded all of it.
        raise SidecarDiscarded(
            f"KiCad silently discarded {path}: the verification canary did not "
            f"fire here, but does fire on this board on its own. Every rule in "
            f"the file is therefore inactive. This exits 0 with an empty stderr, "
            f"so it can only be caught by checking."
        )
    else:
        state = INDETERMINATE
        logger.warning(
            "Could not verify %s took effect: this board has no copper track for "
            "the canary to catch, so its rules cannot be observed firing.", path
        )

    # Every rule that was asked for appears, including those that found nothing.
    # A zero is a real result -- the board complies -- and dropping the key would
    # make it indistinguishable from a rule that never ran, which is the whole
    # distinction this module exists to preserve.
    counts = {name: hits[name] for name, _, _, _ in rules}
    return {"state": state, "report": strip_canary(report), "hits": counts}
